# Generated by Django 5.2.15 on 2026-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadtimeline',
            name='related_appointment_id',
        ),
        migrations.RemoveField(
            model_name='leadtimeline',
            name='related_followup_id',
        ),
        migrations.RemoveField(
            model_name='leadtimeline',
            name='related_note_id',
        ),
        migrations.AddField(
            model_name='leadtimeline',
            name='related_appointment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtimeline',
            name='related_followup_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtimeline',
            name='related_note_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
