# Generated by Django 5.2.15 on 2026-07-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_leadtimeline_related_appointment_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_appointments', to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('system', 'System'), ('whatsapp', 'WhatsApp')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='notes', to='crm.leadattachment'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='is_rich_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_notes', to='users.employeeprofile'),
        ),
    ]
