# Generated by Django 5.2.15 on 2026-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_alternate_contact_lead_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
