# Generated by Django 5.2.15 on 2026-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_leadnote_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('won', 'Won'), ('lost', 'Lost'), ('converted', 'Converted'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('follow_up', 'Follow-up'), ('archived', 'Archived')], db_index=True, default='open', max_length=20),
        ),
    ]
