# Generated by Django 5.2.15 on 2026-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
