# Generated by Django 5.2.15 on 2026-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_productcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='at_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='classification',
            field=models.CharField(default='Product', max_length=100),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='importance',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='min_stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='opng_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='purch_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='source',
            field=models.CharField(default='Internal Manufacturing', max_length=100),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='std_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='unit',
            field=models.CharField(default='no.s', max_length=50),
        ),
    ]
