# Generated by Django 5.2.15 on 2026-07-30 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_productcatalog_at_store_productcatalog_category_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('source_address', models.TextField(blank=True, null=True)),
                ('shipping_details', models.TextField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('share_email', models.BooleanField(default=False)),
                ('share_whatsapp', models.BooleanField(default=False)),
                ('print_after_save', models.BooleanField(default=False)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_description', models.CharField(max_length=255)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='nos', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
