"""
Lead Core Models
=================
Lead         — The primary entity. Fully normalised, multi-tenant, indexed.
LeadProduct  — Products/services a lead is interested in (M2M details).
"""

import uuid
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

from common.models import TenantBaseModel
from common.validators import validate_mobile


class Lead(TenantBaseModel):
    """
    Central entity of the CRM.

    Design notes:
    - All FK lookups use select_related() in queryset helpers.
    - Composite indexes on high-cardinality filters.
    - lead_number generated by DocumentSequence service on first save.
    - lead_score is computed by ScoreService and stored for fast sorting.
    """

    # ─── Priority ──────────────────────────────────────────────────────────────
    class Priority(models.TextChoices):
        LOW    = 'low',    'Low'
        MEDIUM = 'medium', 'Medium'
        HIGH   = 'high',   'High'
        URGENT = 'urgent', 'Urgent'

    # ─── Status ────────────────────────────────────────────────────────────────
    class Status(models.TextChoices):
        OPEN        = 'open',        'Open'
        IN_PROGRESS = 'in_progress', 'In Progress'
        ON_HOLD     = 'on_hold',     'On Hold'
        WON         = 'won',         'Won'
        LOST        = 'lost',        'Lost'
        CONVERTED   = 'converted',   'Converted'
        CONTACTED   = 'contacted',   'Contacted'
        QUALIFIED   = 'qualified',   'Qualified'
        FOLLOW_UP   = 'follow_up',   'Follow-up'
        ARCHIVED    = 'archived',    'Archived'

    # ─── Identity ───────────────────────────────────────────────────────────────
    lead_number   = models.CharField(max_length=30, blank=True, null=True, db_index=True)
    first_name    = models.CharField(max_length=100)
    last_name     = models.CharField(max_length=100, blank=True, null=True)
    company_name  = models.CharField(max_length=200, blank=True, null=True)

    # ─── Contact ────────────────────────────────────────────────────────────────
    mobile           = models.CharField(max_length=15, validators=[validate_mobile], db_index=True)
    alternate_mobile = models.CharField(max_length=15, blank=True, null=True, validators=[validate_mobile])
    email            = models.EmailField(blank=True, null=True, db_index=True)
    secondary_email  = models.EmailField(blank=True, null=True)
    alternate_contact= models.CharField(max_length=100, blank=True, null=True)
    website          = models.URLField(blank=True, null=True)
    gst_number       = models.CharField(max_length=15, blank=True, null=True)
    pan_number       = models.CharField(max_length=10, blank=True, null=True)
    social_links     = models.JSONField(default=dict, blank=True)

    # ─── Location ───────────────────────────────────────────────────────────────
    address = models.TextField(blank=True, null=True)
    city    = models.CharField(max_length=100, blank=True, null=True)
    state   = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True, default='India')
    pincode = models.CharField(max_length=10, blank=True, null=True)

    # ─── Pipeline ───────────────────────────────────────────────────────────────
    stage  = models.ForeignKey(
        'crm.LeadStage', on_delete=models.PROTECT,
        null=True, blank=True, related_name='leads', db_index=True
    )
    status   = models.CharField(max_length=20, choices=Status.choices, default=Status.OPEN, db_index=True)
    priority = models.CharField(max_length=10, choices=Priority.choices, default=Priority.MEDIUM)

    # ─── Classification ─────────────────────────────────────────────────────────
    source = models.ForeignKey(
        'crm.LeadSource', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='leads'
    )
    tags = models.ManyToManyField(
        'crm.LeadTag', blank=True, related_name='leads'
    )
    lost_reason = models.ForeignKey(
        'crm.LostReason', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='leads'
    )
    lost_notes = models.TextField(blank=True, null=True)

    # ─── Opportunity ────────────────────────────────────────────────────────────
    estimated_value    = models.DecimalField(max_digits=14, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    product_interested = models.CharField(max_length=200, blank=True, null=True)
    requirements       = models.TextField(blank=True, null=True)

    # ─── Assignment ─────────────────────────────────────────────────────────────
    assigned_to = models.ForeignKey(
        'users.EmployeeProfile', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='assigned_leads', db_index=True
    )

    # ─── Engagement Dates ───────────────────────────────────────────────────────
    last_contact_date   = models.DateField(null=True, blank=True)
    next_followup_date  = models.DateField(null=True, blank=True)
    last_followup_date  = models.DateField(null=True, blank=True)
    won_at              = models.DateTimeField(null=True, blank=True)
    lost_at             = models.DateTimeField(null=True, blank=True)
    converted_at        = models.DateTimeField(null=True, blank=True)

    # ─── Scoring & Flags ────────────────────────────────────────────────────────
    lead_score  = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(100)],
        help_text='0–100 computed by ScoreService'
    )
    is_starred    = models.BooleanField(default=False, db_index=True)
    is_duplicate  = models.BooleanField(default=False)
    duplicate_of  = models.ForeignKey(
        'self', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='duplicates'
    )

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['company', 'stage']),
            models.Index(fields=['company', 'assigned_to']),
            models.Index(fields=['company', 'status']),
            models.Index(fields=['company', 'created_at']),
            models.Index(fields=['company', 'is_starred']),
            models.Index(fields=['company', 'next_followup_date']),
            models.Index(fields=['mobile']),
            models.Index(fields=['email']),
        ]

    def __str__(self):
        return f"{self.lead_number or self.pk} — {self.full_name}"

    @property
    def full_name(self) -> str:
        parts = [p for p in [self.first_name, self.last_name] if p]
        return ' '.join(parts) or self.company_name or 'Unknown'

    def mark_won(self):
        self.status = self.Status.WON
        self.won_at = timezone.now()
        self.save(update_fields=['status', 'won_at', 'updated_at'])

    def mark_lost(self):
        self.status = self.Status.LOST
        self.lost_at = timezone.now()
        self.save(update_fields=['status', 'lost_at', 'updated_at'])


class LeadProduct(TenantBaseModel):
    """
    Detailed product/service interest attached to a lead.
    Supports multiple products per lead.
    """
    lead            = models.ForeignKey(Lead, on_delete=models.CASCADE, related_name='products')
    product_name    = models.CharField(max_length=200)
    quantity        = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    estimated_price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    unit            = models.CharField(max_length=50, blank=True, null=True)
    notes           = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['lead', 'product_name']

    def __str__(self):
        return f"{self.lead_id} — {self.product_name}"
