# Generated by Django 5.2 on 2026-08-14
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)), ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Leave', 'Leave'), ('Holiday', 'Holiday')], default='Present', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)), ('check_out', models.TimeField(blank=True, null=True)), ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_attendancerecord_related', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_attendancerecord_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_attendancerecord_updated', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.employeeprofile')),
            ], options={'ordering': ['-date', 'employee__first_name'], 'unique_together': {('company', 'employee', 'date')}},
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)), ('is_active', models.BooleanField(default=True)),
                ('month', models.DateField(help_text='Use the first day of the payroll month.')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Paid', 'Paid')], default='Draft', max_length=20)), ('paid_on', models.DateField(blank=True, null=True)), ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_salaryrecord_related', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_salaryrecord_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_salaryrecord_updated', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='users.employeeprofile')),
            ], options={'ordering': ['-month', 'employee__first_name'], 'unique_together': {('company', 'employee', 'month')}},
        ),
    ]
